### ISSUE TITLE
How do I install this app?

### ISSUE THREAD

**Issue by Saucepicious** [DerekSelander/AirDrop-Hack#1]
How do install Airdrop-Hack? I've used things like Cydia Impactor to install IPAs and various Jailbreaks. I'm unsure how to install this though but I would love to try it out! Thank you.

**Comment by DerekSelander** [comment]
You'd have to sign and install it via Xcode if you have a valid developer ID.  If jailbroken, you can ad-hoc sign it, then install it via tools like mobdevim or https://www.libimobiledevice.org.  You'll run into various problems depending on iOS version, this code should only work in iOS 11
